config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "welcome#index"

  draw :users
  draw :subscriptions
  draw :payments

  resources :posts do
    member do
      post :analyze
    end
  end

  resources :conversations, only: %i[show create] do
    resources :messages, only: %i[create]
  end

  # Health check route
  get "/up", to: ->(_env) { [204, {}, [""]] }
end

app/models/concerns/user/omniauth.rb
# frozen_string_literal: true

module User::Omniauth
  extend ActiveSupport::Concern

  class_methods do
    def from_omniauth(auth)
      OmniauthUser.find_or_create(auth).value_or(nil)
    end
  end
end

app/models/concerns/user/status_manager.rb
# frozen_string_literal: true

module User::StatusManager
  extend ActiveSupport::Concern

  included do
    has_many :user_status_logs, class_name: "UserStatusLog", dependent: :destroy
    has_enumeration_for :user_status_id, with: UserStatuses

    after_create_commit :enqueue_log_status_change
  end

  def online?
    @online ||= begin
      user_status_boolean = Kredis.boolean("userstatus")
      user_status_boolean.value = Rails.redis.get("user_status_online:#{id}")
      user_status_boolean.value
    end
  end

  def enqueue_log_status_change
    User::LogStatusChangeJob.perform_later(id, user_status_id)
  end

  def last_seen_at
    user_status_logs.last&.created_at || created_at
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  data                   :text
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           not null
#  provider               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  uid                    :string
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_status_id         :bigint           default(1), not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_provider_and_uid      (provider,uid) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_user_status_id        (user_status_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_status_id => user_statuses.id)
#
class User < ApplicationRecord
  include StatusManager
  include Omniauth

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[google_oauth2 github]

  has_many :posts, dependent: :destroy, class_name: "Post"
  has_many :messages, dependent: :destroy, class_name: "Message"
  has_many :conversations, foreign_key: :sender_id, dependent: :destroy, inverse_of: :sender, class_name: "Conversation"
  has_one :subscription, dependent: :destroy, class_name: "Subscription"
  has_one_attached :avatar

  serialize :data, coder: YAML, type: Hash

  validates :name, presence: true, length: { minimum: 2, maximum: 100 }

  before_save :add_faker_avatar, :set_default_user_status, if: :new_record?
  after_create :set_example_posts

  private

  def set_default_user_status
    self.user_status_id = UserStatus.where(id: UserStatuses::OFFLINE).select(:id).first.id
  end

  def add_faker_avatar
    data[:avatar_url] = Faker::Avatar.image
  end

  def set_example_posts
    10.times { posts.create(title: Faker::Lorem.sentence, content: Faker::Lorem.paragraph) }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    handle_auth(SocialNetwork::GOOGLE)
  end

  def github
    handle_auth(SocialNetwork::GITHUB)
  end

  private

  def handle_auth(provider)
    if user.present?
      successful_authentication(user, provider)
    else
      failed_authentication(provider)
    end
  end

  def user
    @user ||= User.from_omniauth(auth)
  end

  def successful_authentication(user, provider)
    sign_out_all_scopes
    flash[:success] = t "devise.omniauth_callbacks.success", kind: provider.capitalize
    sign_in_and_redirect user, event: :authentication
  end

  def failed_authentication(provider)
    flash[:alert] =
      t "devise.omniauth_callbacks.failure", kind: provider, reason: "#{auth.info.email} is not authorized."
    redirect_to new_user_session_path
  end

  def auth
    @auth ||= request.env["omniauth.auth"]
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update] # rubocop:disable Rails/LexicallyScopedActionFilter

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |resource|
      DeviceMailer.registration_email(resource).deliver_later if resource.persisted?
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :set_conversation_users_with_pagy, only: %i[index]
  before_action :set_profile_user, only: %i[show]

  def index
  end

  def show
  end

  private

  def set_profile_user
    @user = params[:id].present? ? User.find(params[:id]) : current_user
  end

  def set_conversation_users_with_pagy
    @pagy, @users = pagy(UserQuery.all_except(current_user), items: 5)
  end
end

app/views/users/_status.html.erb
<span id="user-status-<%= user.id %>">
  (<% if user.online? %>
    online
  <% else %>
    <%= time_ago_in_words(user.last_seen_at) %>
  <% end %>)
</span>

app/views/users/_users.html.erb
<div id="users">
  <% @users.each do |user| %>
    <%= link_to user_path(user), class: "link-dark text-decoration-none" do %>
      <div class="col-md-4 offset-md-4">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-0">
              <%= user.name %>
            </h3>
            <p class="text-muted">ID: <%= user.id %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="text-center">
  <h1 class="mb-5">Open Chat</h1>
</div>

<div id="users">
  <%= render partial: "users", locals: { posts: @users } %>
  <div data-controller="pagy-initializer">
    <%== render partial: "pagy/bootstrap_nav", locals: { pagy: @pagy } %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="card-body">
  <div class="d-flex flex-column align-items-center text-center">
<!--  <img src="<%#= @user.image %>" width="150" style="border-radius: 100px;">-->
    <div class="mt-3">
      <h4><%= current_user.name %></h4>
      <% if current_user %><br><br>
        <h2>My Posts</h2><br>
        <% current_user.posts.each do |post| %>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= post.title %></h5>
              <p class="card-text"><%= post.body %></p>
              <p class="card-text"><%= post.created_at %></p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
        <% end %>
      <% else %>
        <%= link_to "💬 Message" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <div class="py-5 d-flex justify-content-center">
    <img src="<%= @user.data[:avatar_url] %>" class="rounded-circle avatar">
  </div>

  <h1 class="mb-5"><%= @user.name %></h1>
  <p class="text-muted"><%= t('user_profile.id', id: @user.id) %></p>

  <% if @user.subscription&.premium? %>
    <div class="mb-3">
      <%= button_to t('user_profile.cancel_subscription'), cancel_subscriptions_path, class: "btn btn-danger", method: :post, form: { data: { turbo_confirm: t('are_you_sure') } } %>
    </div>
    <div>
      <p class="text-muted"> <%= t('user_profile.premium_member_until', date: @user.subscription&.paid_until&.strftime("%d %B %Y")) %> </p>
    </div>
  <% elsif @user == current_user %>
    <% if @user.subscription&.pending? %>
      <p class="text-muted"> <%= t('user_profile.your_subscription_is_pending') %> </p>
    <% else %>
      <%= button_to t('user_profile.subscribe'), subscriptions_path, class: "btn btn-dark btn-gradient", method: :post, form: { data: { turbo: false } } %>
    <% end %>
  <% end %>

  <% unless @user == current_user %><br>
    <%= form_with(url: conversations_path, method: :post, data: { turbo: false }) do |form| %>
      <%= form.hidden_field :receiver_id, value: @user.id %>
      <button type="submit" class="btn p-2 button-as-icon">
        <span class="fa-stack fa-lg">
          <i class="fas fa-circle fa-stack-2x" style="color: #000000"></i>
          <i class="fa-regular fa-message fa-stack-1x fa-inverse" style="color: #ffffff;"></i>
        </span>
      </button>
    <% end %>
  <% end %>

  <div class="py-3 d-flex justify-content-center">
    <div class="w-50">
      <div class="border-bottom"></div>
    </div>
  </div>
</div>