config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "welcome#index"

  draw :users
  draw :subscriptions
  draw :payments

  resources :posts do
    member do
      post :analyze
    end
  end

  resources :conversations, only: %i[show create] do
    resources :messages, only: %i[create]
  end

  # Health check route
  get "/up", to: ->(_env) { [204, {}, [""]] }
end

app/models/concerns/post/searchable.rb
# frozen_string_literal: true

module Post::Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks unless Rails.env.test?

    settings index: { number_of_shards: 1 } do
      mappings dynamic: "false" do
        indexes :title
        indexes :content, type: "text"
      end
    end
  end

  def as_indexed_json(_options = {})
    as_json(
      include: {
        rich_text_content: { only: :body }
      }
    ).tap do |data|
      data[:content] = content.to_plain_text
    end
  end

  class_methods do
    def search(query)
      params = {
        query: {
          multi_match: {
            query:,
            fields: %w[title content]
          }
        }
      }

      __elasticsearch__.search(params).records
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  data       :jsonb            not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_posts_on_data     (data) USING gin
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  include Searchable

  validates :title, :content, presence: true
  validates :title, length: { minimum: 2, maximum: 200 }

  has_rich_text :content
  db_belongs_to :user

  serialize :data, coder: SymbolKeysSerializer

  before_save :reset_analyze_result, if: :content_changed?

  private

  def reset_analyze_result
    data[:analyze_result] = nil
  end

  def content_changed?
    content.body_changed?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include Pagy::Backend
  include ResourceResponseHandling

  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy analyze]
  before_action :set_posts_with_pagy, only: %i[index]

  def index
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    respond_with_resource(@post, notice: I18n.t("posts.create.success"))
  end

  def update
    @post.assign_attributes(post_params)
    respond_with_resource(@post, notice: I18n.t("posts.update.success"))
  end

  def destroy
    destroy_resource(@post, notice: I18n.t("posts.destroy.success"))
  end

  def analyze
    DiaryAnalyzer.call(post: @post, user: current_user)

    redirect_to resource_path(@post), notice: I18n.t("posts.analyze.success")
  rescue AnalysisError, PremiumNotFoundError => e
    redirect_to resource_path(@post), alert: e.message
  end

  private

  def set_posts_with_pagy
    @pagy, @posts = pagy(PagyPostsFetcher.call(search_query: params[:search_query], user: current_user), items: 5)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content).tap { |params| params[:user_id] = current_user.id }
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  include Pagy::Frontend

  def emotions(post)
    post.data.dig(:analyze_result, :emotions)&.join(", ")
  end

  def keywords(post)
    post.data.dig(:analyze_result, :keywords)&.join(", ")
  end

  def recommendations(post)
    post.data.dig(:analyze_result, :recommendations)&.join(", ")
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-5">
    <div class="col-md-4 offset-md-4">
      <div class="mb-3 text-center">
        <%= form.label :title, t("post.title"),  style: "display: block", class: "form-label" %>
        <%= form.text_field :title, class: "form-control", placeholder: t("post.title_example") %>
      </div>
    </div>
  </div>

  <div class="mb-3">
    <%= form.rich_text_area :content, class: "form-control", style: "min-height: 300px;", placeholder: t("post.content_example") %>
  </div>

  <div class="text-center">
    <%= form.submit t("post.save"), class: "btn btn-dark" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-md-6 offset-md-3">
  <article class="blog-post p-3">
    <h2 class="display-5 link-body-emphasis mb-1"><%= post.title %></h2>
    <p class="blog-post-meta fst-italic"><%= post.created_at.strftime("%B %d, %Y") %> by <%= link_to post.user.name, user_path(post.user), style: "text-decoration: none; color: #000000;" %></p>

    <div class="py-3 d-flex justify-content-center">
      <div class="w-100">
        <div class="border-bottom"></div>
      </div>
    </div>

    <%= post.content %>

    <div class="py-3 d-flex justify-content-center">
      <div class="w-100">
        <div class="border-bottom"></div>
      </div>
    </div>

    <% if post.data[:analyze_result].present? %>
      <div class="d-flex justify-content-center">
        <button type="button" class="btn-analyze" data-bs-toggle="modal" data-bs-target="#analyzeModal">
          <i class="fas fa-chart-line"></i> <%= t("analysis_result.show") %>
        </button>
      </div>

      <div class="modal fade" id="analyzeModal" tabindex="-1" aria-labelledby="analyzeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="analyzeModalLabel"><%= t("analysis_result.title") %></h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div>
                <h5><%= t("analysis_result.emotions") %></h5>
                <p><%= emotions(post) %> </p>
              </div>
              <div>
                <h5><%= t("analysis_result.keywords") %></h5>
                <p><%= keywords(post) %></p>
              </div>
              <div>
                <h5><%= t("analysis_result.recommendations") %></h5>
                <p><%= recommendations(post) %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% else %>
      <div class="d-flex justify-content-center">
        <%= form_with url: analyze_post_path(@post), method: :post, local: true, class: "analyze-form",
                      data: { controller: "spinner", action: "turbo:submit-start->spinner#showSpinner" } do %>
          <button type="submit" class="btn-analyze">

            <span class="icon-container">
              <i id="icon-robot" class="fa-solid fa-robot fa-fw"></i>
              <i id="icon-spinner" class="fa fa-spinner fa-spin" style="display: none;"></i>
            </span>
            <span class="text"><%= t("post.ai_analyze") %></span>
          </button>

        <% end %>
      </div>
  <% end %>
  </article>
</div>

app/views/posts/_posts.html.erb
<div id="posts">
  <% posts.each do |post| %>
    <%= link_to post_path(post), class: "link-dark text-decoration-none" do %>
      <div class="col-md-4 offset-md-4">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-0">
              <%= post.title %>
            </h3>
            <div class="mb-1 text-body-secondary"><%= post.created_at.strftime("%B %-d, %Y") %></div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <h1 class="mb-5">Editing post</h1>
</div>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="text-center">
  <h1 class="mb-5"><%= t("navbar.memories") %></h1>
</div>

<div id="posts">
  <%= render partial: "posts", locals: { posts: @posts } %>
  <div data-controller="pagy-initializer">
    <%== render partial: "pagy/bootstrap_nav", locals: { pagy: @pagy } %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="text-center">
  <h1 class="mb-5"><%= t("post.new_post") %></h1>
</div>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= render @post %>

<div class="col-md-6 offset-md-3 text-center">
  <div class="d-flex justify-content-center">
    <%= link_to edit_post_path(@post) do %>
      <div class="p-2">
        <span class="fa-stack fa-lg">
          <i class="fa-solid fa-pen-to-square fa-stack-1x fa-inverse" style="color: #000000;"></i>
        </span>
      </div>
    <% end %>

    <%= button_to @post, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "button-as-icon" do %>
      <div class="p-2">
        <span class="fa-stack fa-lg">
          <i class="fa-solid fa-trash fa-stack-1x fa-inverse" style="color: #000000;"></i>
        </span>
      </div>
    <% end %>
  </div>
</div>